### PR TITLE
Save incremental import depth setting

### PR DESCRIPTION
**Pull request by tpasternak**
This commit was already merged to master, but reverted due to https://github.com/pantsbuild/intellij-pants-plugin/issues/471

ORIGINAL MESSAGE:

Before this commit, IntelliJ plugin was asking for incremental import
depth each time, even when doing refresh. The depth value was not
saved anywhere.

Now, the incremental import depth parameter is saved alongside other
settings, and may be configured in the same place as others.

### CODE REVIEW

**Comment by wisechengyi** [comment]
Bump. CI has been fixed. Thanks!

**Comment by tpasternak** [comment]
Is this still needed?

**Comment by wisechengyi** [comment]
Yes, sorry! Merging.

**Comment by tpasternak** [comment]
Np :) thanks

**Pull request merged**
