### PR TITLE
Don't reference removed contrib plugins

### PR DESCRIPTION
**Pull request by mzarnowski**
See:
- https://github.com/pantsbuild/pants/commit/8ea25c26e863af84f081ace36b16b5c0f57a0aff
- https://github.com/pantsbuild/pants/commit/4453796268d86e603c4361e7f9896b1ca54f08c1
- https://groups.google.com/forum/#!topic/pants-devel/ngMZRIJvwHM

### CODE REVIEW

**Comment by marek1840** [comment]
The CI fails since the `.cache/pants` directory is cached, while newest master contains changes linked in the description. Could it be restarted with clean cache, @wisechengyi ?

**Comment by wisechengyi** [comment]
CI recently stopped to vet against pants master, is this still needed?

**Comment by marek1840** [comment]
I just pulled newest master and still got:
```
FAILURES!!!
                     Tests run: 67,  Failures: 6

tests:jvm-integration
    tests:jvm-integration
com.twitter.intellij.pants.integration.OSSPantsJavaExamplesIntegrationTest#testAntl3                          com.twitter.intellij.pants.integration.OSSPantsJavaExamplesIntegrationTest#testAntl4
com.twitter.intellij.pants.integration.OSSPantsJavaExamplesIntegrationTest#testJaxb
com.twitter.intellij.pants.integration.TargetFileCompletionIntegrationTest#testDependencies
com.twitter.intellij.pants.integration.TargetFileCompletionIntegrationTest#testJavaLibCompletions
com.twitter.intellij.pants.integration.TargetFileCompletionIntegrationTest#testScalaLibCompletions
```

Merging this PR still fixed those issues.

**Comment by wisechengyi** [comment]
closing. seems no longer relevant.

**Pull request closed without merging**
