### PR TITLE
Improve "BSP Amend" testability

### PR DESCRIPTION
**Pull request by tpasternak**
Allow amending programatically, bypassing the "BSP Amend" window. Potentially useful when testing

### CODE REVIEW

**Comment by tpasternak** [comment]
Blocked by https://github.com/pantsbuild/intellij-pants-plugin/pull/532

**Comment by olafurpg** [comment]
The blocking PR has been merged now, is this PR ready for review?

**Comment by tpasternak** [comment]
Yes, I think it can be merged

**Comment by olafurpg** [comment]
cc/ @wisechengyi

**Pull request merged**
