### PR TITLE
Set VcsRoot manually 

### PR DESCRIPTION
**Pull request by tpasternak**
Since IJ 2020.2, the VcsRoot is not set automatically, so we have to do it manually.

The problem has been found during probe tests upgrade to 2020.2 by @lukaszwawrzyk

### CODE REVIEW

**Comment by wisechengyi** [comment]
I'll wait for the ide probe patch to land so the diff is more reviewable, alternatively, not sure if this can be diff'ed off master directly.

**Comment by olafurpg** [comment]
Is there anything blocking the ide-probe PR from being merged? The CI is green.

**Comment by wisechengyi** [comment]
LGTM. Not sure if there's any minor follow up per comments on https://github.com/pantsbuild/intellij-pants-plugin/pull/545, 
or shall I merge it?

**Comment by olafurpg** [comment]
The only unresolved comment is minor. I think it’s ok to merge.

**Comment by wisechengyi** [comment]
github seems to fail to show the updated diff from master...

**Comment by tpasternak** [comment]
Oh, please don't merge this in this form. I just wanted to check the results of the CI, as this commit is baselined on @lukaszwawrzyk 's branch

**Comment by tpasternak** [comment]
please don't merge it in this form, I only wanted to run the CI tests with @lukaszwawrzyk probe-202 baseline

**Pull request closed without merging**
