### PR TITLE
Add IdeProbe - test framework for IntelliJ plugins

### PR DESCRIPTION
**Pull request by marek1840**

### CODE REVIEW

**Comment by marek1840** [comment]
It seems like I cannot create a Github Actions workflow - only repository collaborators can. Could you help me here @wisechengyi ? 
Could you add [this file](https://github.com/pantsbuild/intellij-pants-plugin/pull/513/files#diff-7533818754176277616b853284b724f0) to the master branch? This way I could rebase my PR and hopefully get Github Actions to trigger and check this PR correctly.

image

**Comment by wisechengyi** [comment]
Done: https://github.com/pantsbuild/intellij-pants-plugin/commit/cfb201c761e2b6bedd4afc2695c8c4f80f82b010

**Comment by marek1840** [comment]
> Done: [cfb201c](https://github.com/pantsbuild/intellij-pants-plugin/commit/cfb201c761e2b6bedd4afc2695c8c4f80f82b010)

Sorry to bother you again, @wisechengyi. It turns out the directory must remain the same, github won't pick it up from repository root - could you move it to `.github/workflows/test-ide-probe.yml`?

**Comment by marek1840** [comment]
Closing - will be published under its own repository at a later date

**Pull request closed without merging**
