### PR TITLE
Upgrade to 2018.1 compatibility

### PR DESCRIPTION
**Pull request by wisechengyi**
Also addresses #327

### CODE REVIEW

**Comment by wisechengyi** [comment]
Will merge as #334

**Comment by wisechengyi** [comment]
Plan to merge this by EOD.

**Comment by sproshev** [comment]
Seems like plugin was published with wrong `Compatible builds` value

https://plugins.jetbrains.com/plugin/7412-pants-support

**Comment by wisechengyi** [comment]
@sproshev ah the build number 1.8.1 may be a bit confusing, but it is for 173.x intellij. 

Builds for 181.x branch would start 1.9.0 for pants plugin

**Comment by sproshev** [comment]
@wisechengyi I see, thanks for clarifying!

**Pull request merged**
