### PR TITLE
Add GUI for `faspass amend` command

### PR DESCRIPTION
**Pull request by tpasternak**
Allows user to include (or remove) new pants targets into already
imported project

### CODE REVIEW

**Comment by tpasternak** [comment]
There are some opportunities to improve user experience which maybe achieved with relatively small effort:
1. Auto-completion
2. Prefetching targets into cache while user is typing.

**Comment by tpasternak** [comment]
Labels changed and small parsing improvement added

**Comment by olafurpg** [comment]
I just tried this again and it's working well :+1: 

If it's easy to implement, I'm wondering if we could somehow warn the user about pressing "OK" to save the amendment when there are 0 matching Pants targets? I don't think we should prevent the user from pressing "OK" in this case, but there's currently no strong visual hint (for example color or warning message) that pressing OK will most likely cause the refresh to fail.

**Comment by olafurpg** [comment]
Otherwise, LGTM!

**Comment by tpasternak** [comment]
Added such a warning. Please let me know if it's enough. We can add "Are you sure?" message box as well.

image

**Comment by olafurpg** [comment]
Is the CI failure expected?

**Comment by tpasternak** [comment]
No, it's not, I pushed a commit to rerun

**Comment by olafurpg** [comment]
@wisechengyi any chance we could merge this change?

**Pull request merged**
