### PR TITLE
allow user to specify the default run configuration

### PR DESCRIPTION
**Pull request by mrkb80**
saving potentially thousands of mouse clicks.

### CODE REVIEW

**Comment by mrkb80** [comment]
If possible, it would be nice to back port this to the 1.11.1 release so users of 2018.* can also take advantage of this.

**Comment by wisechengyi** [comment]
Seeing the following when trying this out. Also on the high level, is the goal to remember what kind of run configuration was picked the first time, the remember it when we are creating another run configuration on a different class? E.g. there are 3 kinds of run configs, pants, junit, and scala runner. So if we select scala config the first time, it will always to be scala runner for the next class?
```
java.lang.NullPointerException
	at com.twitter.intellij.pants.execution.DefaultRunConfigurationSelector.registerConfigs(DefaultRunConfigurationSelector.java:26)
	at com.twitter.intellij.pants.components.impl.PantsProjectComponentImpl$1.run(PantsProjectComponentImpl.java:113)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:360)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$queueSmartModeActivity$3(StartupManagerImpl.java:166)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$runWhenSmart$0(DumbServiceImpl.java:232)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$runWhenProjectIsInitialized$6(StartupManagerImpl.java:392)
	at com.intellij.ui.GuiUtils.invokeLaterIfNeeded(GuiUtils.java:377)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runWhenProjectIsInitialized(StartupManagerImpl.java:394)
	at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:224)
	at com.intellij.ide.startup.impl.StartupManagerImpl.queueSmartModeActivity(StartupManagerImpl.java:166)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$400(StartupManagerImpl.java:48)
	at com.intellij.ide.startup.impl.StartupManagerImpl$1.lambda$run$0(StartupManagerImpl.java:196)
	at java.util.ArrayList.forEach(ArrayList.java:1251)
	at com.intellij.ide.startup.impl.StartupManagerImpl$1.run(StartupManagerImpl.java:196)
	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:380)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:372)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$pollQueueLater$0(TransactionGuardImpl.java:74)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:742)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:691)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by mrkb80** [comment]
Hey @wisechengyi 
Yes, you are correct.  The idea is to let the user specify in the pants-plugin configuration UI which default runner they would like to use (if any) and then persist this.  We do not use Scala, so I am less familiar with how the run configurations are produced.  Do you know if it has its own run configuration producer like pants/junit?  If so, I can easily add support for that.  Otherwise, this would not work for scala (but would leave existing behavior untouched).

**Comment by mrkb80** [comment]
> Seeing the following error when trying this out. Also on the high level, is the goal to remember what kind of run configuration was picked the first time, the remember it when we are creating another run configuration on a different class? E.g. there are 3 kinds of run configs, pants, junit, and scala runner. So if we select scala config the first time, it will always to be scala runner for the next class?
> 
> ```
> java.lang.NullPointerException
> 	at com.twitter.intellij.pants.execution.DefaultRunConfigurationSelector.registerConfigs(DefaultRunConfigurationSelector.java:26)
> 	at com.twitter.intellij.pants.components.impl.PantsProjectComponentImpl$1.run(PantsProjectComponentImpl.java:113)
> 	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:360)
> 	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$queueSmartModeActivity$3(StartupManagerImpl.java:166)
> 	at com.intellij.openapi.project.DumbServiceImpl.lambda$runWhenSmart$0(DumbServiceImpl.java:232)
> 	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$runWhenProjectIsInitialized$6(StartupManagerImpl.java:392)
> 	at com.intellij.ui.GuiUtils.invokeLaterIfNeeded(GuiUtils.java:377)
> 	at com.intellij.ide.startup.impl.StartupManagerImpl.runWhenProjectIsInitialized(StartupManagerImpl.java:394)
> 	at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:224)
> 	at com.intellij.ide.startup.impl.StartupManagerImpl.queueSmartModeActivity(StartupManagerImpl.java:166)
> 	at com.intellij.ide.startup.impl.StartupManagerImpl.access$400(StartupManagerImpl.java:48)
> 	at com.intellij.ide.startup.impl.StartupManagerImpl$1.lambda$run$0(StartupManagerImpl.java:196)
> 	at java.util.ArrayList.forEach(ArrayList.java:1251)
> 	at com.intellij.ide.startup.impl.StartupManagerImpl$1.run(StartupManagerImpl.java:196)
> 	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:380)
> 	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:372)
> 	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
> 	at com.intellij.openapi.application.TransactionGuardImpl.lambda$pollQueueLater$0(TransactionGuardImpl.java:74)
> 	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
> 	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
> 	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
> 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
> 	at java.awt.EventQueue.access$500(EventQueue.java:98)
> 	at java.awt.EventQueue$3.run(EventQueue.java:715)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
> 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:742)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:691)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
> ```

This should be fixed in the latest push.

**Comment by mrkb80** [comment]
@wisechengyi did you get a chance to look at this again?  Not sure about the build failure.  I have never been able to get the test to run locally.

**Comment by wisechengyi** [comment]
Hey @mrkb80 sorry for the delay. The CI failure is expected, so no worries.

Can you clarify what the behavior is now? Once user selects a certain runner, is it possible to switch if they want to?

**Comment by mrkb80** [comment]
Hey @wisechengyi no worries on the delay.

The behavior is exactly as you described above.  And the user can use the pants configuration menu to change to a different default runner or back to all the runners (at a global level).  So current behavior is preserved, this is only an additional option.

**Comment by wisechengyi** [comment]
Thanks! will take a closer look by EOD

**Comment by wisechengyi** [comment]
Thanks, @mrkb80! Looks good. One small thing is that the UI may be confusing to users. How do you feel about adding a line above the dropdown: `Choose default test runner`?

Screen Shot 2019-04-25 at 2 15 04 PM

**Comment by mrkb80** [comment]
Great idea.  I actually could not figure out how to add a label.  Do you know how (intellij sdk is confusing)?

On Apr 25, 2019 5:18 PM, Yi Cheng <notifications@github.com> wrote:

Thanks, @mrkb80<https://github.com/mrkb80>! Looks good. One small thing is that the UI may be confusing to users. How do you feel about adding a line above the dropdown: Choose default test runner?

[Screen Shot 2019-04-25 at 2 15 04 PM]<https://user-images.githubusercontent.com/596358/56768974-af7b6180-6764-11e9-9808-4abfd3a64a09.png>

**Comment by mrkb80** [comment]
@wisechengyi Any chance you can take a look at the comments above and give me some pointers?

**Comment by mrkb80** [comment]
@wisechengyi 
Are you ok with taking this as is?

**Comment by wisechengyi** [comment]
Hey sorry, haven't been able to look this lately. There should be some examples in the repo. For example, search for the string that's used as label, then find out where and how it used.

If not, I can try to patch this this weekend.

**Comment by tpasternak** [comment]
Hi, @mrkb80 . I talked to @wisechengyi about this PR. Would you mind if I rebased to 2019.3 and finalize the task?

**Comment by mrkb80** [comment]
> Hi, @mrkb80 . I talked to @wisechengyi about this PR. Would you mind if I rebased your code to 2019.3 and finalize the task?

That sounds great!   Please do!

**Comment by tpasternak** [comment]
In general I think the idea of the feature is very good, and it may save thousands of clicks indeed. Unfortunately, I think the code should not be merged in this form.

1. De facto it doesn't set the defaults. It disables all run configuration generators except the selected ones.
2. It doesn't take into account that potentially there may be more than just two run configuration generators.
3. In general it's not directly related to Pants Support functionality. It can be useful in any context, with any build system.

On the other hand, this feature could be implemented in a separate plugin. Instead of disabling all other generators except the default one, we could add a new, "Run default" action that just selects the configured generator. Then, we could do both: "run default" and "run non-default".

**Comment by mrkb80** [comment]
> @wisechengyi In general I think the idea of the feature is very good, and it may save thousands of clicks indeed. Unfortunately, I think the code should not be merged in this form.
> 
> 1. De facto it doesn't set the defaults. It disables all run configuration generators except the selected ones.
> 2. It doesn't take into account that potentially there may be more than just two run configuration generators.
> 3. In general it's not directly related to Pants Support functionality. It can be useful in any context, with any build system.
> 
> On the other hand, this feature could be implemented in a separate plugin. Instead of disabling all other generators except the default one, we could add a new, "Run default" action that just selects the configured generator. Then, we could do both: "run default" and "run non-default".

Per pont 1:
It would be fairly easy to address this with a little refactoring.

Per point 2:
I agree that this will only let you select from two run configurations as your default, but I guess I have never really run into a scenario where I would have more than one build system in the same project. In the pants plugin view, it seems you would only ever have the intellij junit wrapper and the pants command line junit wrapper.  

Per point 3:
I suppose it would be possible to pull this out into a separate plugin, but I have never needed this functionality outside of using pants (however, I admit I typically use maven or gradle).

If you think it is not suited for use as part of the pants plugin, I have no problem closing this PR.  It seems like a fairly benign change to the plugin (taking into account some modification to point 1 above which I am happy to address).  It would really only have an impact, should the user decide to modify the settings.

**Comment by tpasternak** [comment]
> Per pont 1:
> It would be fairly easy to address this with a little refactoring.

Yes, that's true. But even if the default runner is set, it should be somehow possible to run the non-default configuration, so we shouldn't just deregister the extensions (btw `registerExtension` and `unregisterExtension` are now deprecated).

> Per point 2:
> I agree that this will only let you select from two run configurations as your default, but I guess I have never really run into a scenario where I would have more than one build system in the same project. In the pants plugin view, it seems you would only ever have the intellij junit wrapper and the pants command line junit wrapper.

Not only build systems may register extensions there. For example, JUnit plugin is not related to any build system, but it registers it.

> Per point 3:
> I suppose it would be possible to pull this out into a separate plugin, but I have never needed this functionality outside of using pants (however, I admit I typically use maven or gradle).

So maybe we could simply limit the scope of it to a special extensions named "Run with pants"? It would be presended alongside "Run", when you right-click the test name. It's job would be to execute Pants run configuration without asking for anything. This wouldn't require to interfere with other plugins' extensions, it would be just Pants-specific.

**Comment by mrkb80** [comment]
> > Per pont 1:
> > It would be fairly easy to address this with a little refactoring.
> 
> Yes, that's true. And even if the default runner is set, it should be somehow possible to run the non-default configuration, so we shouldn't just deregister the extensions (expecially because `registerExtension` and `unregisterExtension` are now deprecated).
> 
> > Per point 2:
> > I agree that this will only let you select from two run configurations as your default, but I guess I have never really run into a scenario where I would have more than one build system in the same project. In the pants plugin view, it seems you would only ever have the intellij junit wrapper and the pants command line junit wrapper.
> 
> Not only build systems may register extensions there. For example, JUnit plugin is not related to any build system, but it registers it.
> 
> > Per point 3:
> > I suppose it would be possible to pull this out into a separate plugin, but I have never needed this functionality outside of using pants (however, I admit I typically use maven or gradle).
> 
> So what do you think about limiting the scope of the PR to a special extension named "Run with pants"? It would be presented alongside "Run", when you right-click the test name. It's job would be to execute Pants run configuration without asking for anything. This wouldn't require to interfere with other plugins' extensions, it would be just Pants-specific.

All good points.  I agree with the final scope.  We should just move the pants runner into its own "Run with Pants" option.

**Comment by wisechengyi** [comment]
closing due to inactivity.

**Pull request closed without merging**
